### PR TITLE
Feature/equip sound effect

### PR DESCRIPTION
**Pull request by yanisakham**
Code Changes:
* added two audio files to client/assets/audio/items
* load audio in Boot.js and configure in Game.js
* played audio for equip weapon in client/src/web_sockets/Inventory.js activate_holding event
* played audio for equip clothing in client/src/web_sockets/Inventory.js activate_clothing event

Currently there is one generic sound for all clothing items and one for all weapon items. I want to have a custom sound depending on the clothing/weapon material, but still not too sure how to identify the item type within the events

### CODE REVIEW

**Comment by Arcanorum** [comment]
Can you confirm the source for the audio files please. Whether they are original pieces, adapted from something else, or have another source. I need to consider asset use based on licenses where applicable.

**Comment by yanisakham** [comment]
The clothing audio clip is from openGameArt's inventory_sound_effects collection. The weapon sound effect is the one suggested by Peppsen in the #audio chat  (messaged him asking about the source)

**Comment by yanisakham** [comment]
The second clip is from Soundly through their Soundly Free Library. The sounds in the Soundly Pro and Soundly Free libraries are cleared for commercial use. Any projects created while subscribing to Soundly Pro stay cleared even if you end your subscription. This includes, but is not limited to: podcasts, films, video games.

**Review by Arcanorum — APPROVED** [review]
lgtm.
Have added the attribution note for the OGA asset.
Will clarify about how to differentiate between more specific item types.

**Pull request merged**
